# AlathraFishing.yml
# Created by NuclearDonut47 for the Minecraft server Alathra.

# Tools used in plugin.
# The items used for tools may only be items with nonzero durability.

tools:
  net:
    name: "Net" # Default "Net"
    item: "FISHING_ROD"
    model: 47000 # Default 0
    durability: 4 # Default 64
  fishing_rod:
    name: "Alathran Fishing Rod" # Default "Fishing Rod"
    item: "FISHING_ROD"
    model: 47001 # Default 1
    durability: 4 # Default 64
  trowel:
    name: "Trowel" # Default "Trowel"
    item: "IRON_AXE" # Default "IRON_SHOVEL"
    model: 47050 # Default 2
    durability: 4 # Default 250
  catcher:
    name: "Test" # Default "Catcher"
    item: "IRON_SHOVEL" # Default "IRON_SHOVEL"
    model: 47051 # Default 3
    durability: 4 # Default 250
